import type { ChargingStation } from '../../types/station';

export const MOCK_STATIONS: ChargingStation[] = [
  {
    id: 'zes-001',
    name: 'ZES - İstanbul Havalimanı',
    network: 'ZES',
    address: 'İstanbul Havalimanı Terminal',
    city: 'İstanbul',
    latitude: 41.2753,
    longitude: 28.7519,
    overallStatus: 'available',
    phone: '0850 123 45 67',
    totalAvailable: 4,
    totalConnectors: 6,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 150, status: 'available', pricePerKwh: 9.5 },
      { id: 1, type: 'CCS2', powerKw: 150, status: 'available', pricePerKwh: 9.5 },
      { id: 2, type: 'CHAdeMO', powerKw: 50, status: 'occupied', pricePerKwh: 8.5 },
      { id: 3, type: 'Type2', powerKw: 22, status: 'available', pricePerKwh: 7.0 },
    ],
  },
  {
    id: 'esarj-001',
    name: 'Eşarj - Zorlu Center',
    network: 'Eşarj',
    address: 'Zorlu Center AVM, Beşiktaş',
    city: 'İstanbul',
    latitude: 41.0675,
    longitude: 29.0155,
    overallStatus: 'available',
    phone: '0850 222 33 44',
    totalAvailable: 2,
    totalConnectors: 4,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 120, status: 'available', pricePerKwh: 9.0 },
      { id: 1, type: 'CCS2', powerKw: 120, status: 'occupied', pricePerKwh: 9.0 },
      { id: 2, type: 'Type2', powerKw: 22, status: 'available', pricePerKwh: 7.5 },
      { id: 3, type: 'Type2', powerKw: 22, status: 'out_of_service', pricePerKwh: 7.5 },
    ],
  },
  {
    id: 'trugo-001',
    name: 'Trugo - Kadıköy',
    network: 'Trugo',
    address: 'Bağdat Caddesi No:142, Kadıköy',
    city: 'İstanbul',
    latitude: 40.9739,
    longitude: 29.0743,
    overallStatus: 'occupied',
    phone: '0850 333 44 55',
    totalAvailable: 0,
    totalConnectors: 3,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 180, status: 'occupied', pricePerKwh: 10.0 },
      { id: 1, type: 'CHAdeMO', powerKw: 50, status: 'occupied', pricePerKwh: 8.5 },
      { id: 2, type: 'Type2', powerKw: 22, status: 'occupied', pricePerKwh: 7.0 },
    ],
  },
  {
    id: 'voltrun-001',
    name: 'Voltrun - Levent Metro',
    network: 'Voltrun',
    address: '4. Levent Metro İstasyonu',
    city: 'İstanbul',
    latitude: 41.0780,
    longitude: 29.0128,
    overallStatus: 'available',
    phone: null,
    totalAvailable: 3,
    totalConnectors: 3,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 50, status: 'available', pricePerKwh: 8.0 },
      { id: 1, type: 'Type2', powerKw: 22, status: 'available', pricePerKwh: 6.5 },
      { id: 2, type: 'Type2', powerKw: 22, status: 'available', pricePerKwh: 6.5 },
    ],
  },
  {
    id: 'zes-002',
    name: 'ZES - Ankara Kızılay',
    network: 'ZES',
    address: 'Kızılay Meydanı, Çankaya',
    city: 'Ankara',
    latitude: 39.9199,
    longitude: 32.8543,
    overallStatus: 'available',
    phone: '0850 123 45 67',
    totalAvailable: 2,
    totalConnectors: 4,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 150, status: 'available', pricePerKwh: 9.5 },
      { id: 1, type: 'CCS2', powerKw: 150, status: 'available', pricePerKwh: 9.5 },
      { id: 2, type: 'CHAdeMO', powerKw: 50, status: 'occupied', pricePerKwh: 8.5 },
      { id: 3, type: 'Type2', powerKw: 22, status: 'occupied', pricePerKwh: 7.0 },
    ],
  },
  {
    id: 'esarj-002',
    name: 'Eşarj - İzmir Alsancak',
    network: 'Eşarj',
    address: 'Alsancak, Konak',
    city: 'İzmir',
    latitude: 38.4352,
    longitude: 27.1436,
    overallStatus: 'available',
    phone: '0850 222 33 44',
    totalAvailable: 2,
    totalConnectors: 2,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 120, status: 'available', pricePerKwh: 9.0 },
      { id: 1, type: 'Type2', powerKw: 22, status: 'available', pricePerKwh: 7.5 },
    ],
  },
  {
    id: 'trugo-002',
    name: 'Trugo - Maslak',
    network: 'Trugo',
    address: 'Maslak, Sarıyer',
    city: 'İstanbul',
    latitude: 41.1100,
    longitude: 29.0200,
    overallStatus: 'available',
    phone: null,
    totalAvailable: 1,
    totalConnectors: 2,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 180, status: 'available', pricePerKwh: 10.0 },
      { id: 1, type: 'CHAdeMO', powerKw: 50, status: 'occupied', pricePerKwh: 8.5 },
    ],
  },
  {
    id: 'voltrun-002',
    name: 'Voltrun - Ataşehir',
    network: 'Voltrun',
    address: 'Ataşehir Bulvarı No:12',
    city: 'İstanbul',
    latitude: 40.9923,
    longitude: 29.1244,
    overallStatus: 'out_of_service',
    phone: null,
    totalAvailable: 0,
    totalConnectors: 2,
    connectors: [
      { id: 0, type: 'CCS2', powerKw: 50, status: 'out_of_service', pricePerKwh: 8.0 },
      { id: 1, type: 'Type2', powerKw: 22, status: 'out_of_service', pricePerKwh: 6.5 },
    ],
  },
];
