import type { ChargingStation } from "../../types/station";

export const MOCK_STATIONS: ChargingStation[] = [
  // ─── 1. ZES - İstanbul Havalimanı ───────────────────────────────────────────
  {
    id: "zes-001",
    name: "ZES - İstanbul Havalimanı",
    network: "ZES",
    address: "İstanbul Havalimanı Terminal Caddesi",
    city: "İstanbul",
    district: "Arnavutköy",
    latitude: 41.2753,
    longitude: 28.7519,
    overallStatus: "available",
    phone: "0850 166 0 166",
    totalAvailable: 6,
    totalConnectors: 8,
    isGreenEnergy: false,
    locationType: "highway",
    openingHours: { is24h: true },
    venueName: "İstanbul Havalimanı",
    hasToggPriority: true,
    hasBlockingFee: true,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 180,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 3,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 4,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 2. Eşarj - Zorlu Center AVM ────────────────────────────────────────────
  {
    id: "esarj-001",
    name: "Eşarj - Zorlu Center AVM",
    network: "Eşarj",
    address: "Levazım Mah. Koru Sk. No:2, Beşiktaş",
    city: "İstanbul",
    district: "Beşiktaş",
    latitude: 41.0675,
    longitude: 29.0155,
    overallStatus: "available",
    phone: "0850 346 0 346",
    totalAvailable: 4,
    totalConnectors: 6,
    isGreenEnergy: true,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Zorlu Center AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 360,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 360,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 150,
        status: "occupied",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 3. Trugo - Shell Kadıköy ────────────────────────────────────────────────
  {
    id: "trugo-001",
    name: "Trugo - Shell Kadıköy",
    network: "Trugo",
    address: "Bağdat Cad. No:142, Kadıköy",
    city: "İstanbul",
    district: "Kadıköy",
    latitude: 40.9739,
    longitude: 29.0743,
    overallStatus: "available",
    phone: "0850 222 8 746",
    totalAvailable: 2,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "gas_station",
    openingHours: { is24h: true },
    venueName: "Shell Kadıköy",
    hasToggPriority: true,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 180,
        status: "occupied",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 4. Voltrun - Levent Metro ───────────────────────────────────────────────
  {
    id: "voltrun-001",
    name: "Voltrun - Levent Metro",
    network: "Voltrun",
    address: "4. Levent Metro İstasyonu Yanı, Levent",
    city: "İstanbul",
    district: "Beşiktaş",
    latitude: 41.078,
    longitude: 29.0128,
    overallStatus: "available",
    phone: null,
    totalAvailable: 4,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "parking",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 5. WAT - Akasya AVM İstanbul ───────────────────────────────────────────
  {
    id: "wat-001",
    name: "WAT - Akasya AVM",
    network: "WAT",
    address: "Acıbadem Mah. Çeçen Sk. No:25, Üsküdar",
    city: "İstanbul",
    district: "Üsküdar",
    latitude: 41.0012,
    longitude: 29.0315,
    overallStatus: "available",
    phone: "0850 999 0 928",
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Akasya AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 120,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 120,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 6. 5şarj - Ankara Bilkent ──────────────────────────────────────────────
  {
    id: "5sarj-001",
    name: "5şarj - Bilkent Center",
    network: "5şarj",
    address: "Bilkent Center, Çankaya",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.8686,
    longitude: 32.7486,
    overallStatus: "available",
    phone: "0312 265 0 005",
    totalAvailable: 2,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "09:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Bilkent Center",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 12.49,
        pricePerKwhHPC: 15.99,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 150,
        status: "occupied",
        pricePerKwh: 12.49,
        pricePerKwhHPC: 15.99,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 7. EnYakıt - TEM Bolu Dağı ─────────────────────────────────────────────
  {
    id: "enyakit-001",
    name: "EnYakıt - TEM Bolu Dağı",
    network: "EnYakıt",
    address: "TEM Otoyolu Bolu Dağı Mevkii, Bolu",
    city: "Bolu",
    district: "Merkez",
    latitude: 40.642,
    longitude: 31.625,
    overallStatus: "available",
    phone: "0850 255 0 369",
    totalAvailable: 4,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "highway",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 3,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 8. ZES - Ankara Kızılay ─────────────────────────────────────────────────
  {
    id: "zes-002",
    name: "ZES - Ankara Kızılay",
    network: "ZES",
    address: "Kızılay Meydanı, Çankaya",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.9199,
    longitude: 32.8543,
    overallStatus: "available",
    phone: "0850 166 0 166",
    totalAvailable: 2,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "public",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: true,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 9. Eşarj - İzmir Alsancak ──────────────────────────────────────────────
  {
    id: "esarj-002",
    name: "Eşarj - İzmir Alsancak",
    network: "Eşarj",
    address: "Alsancak Mah. Kıbrıs Şehitleri Cad. No:65, Konak",
    city: "İzmir",
    district: "Konak",
    latitude: 38.4352,
    longitude: 27.1436,
    overallStatus: "available",
    phone: "0850 346 0 346",
    totalAvailable: 2,
    totalConnectors: 3,
    isGreenEnergy: true,
    locationType: "public",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 120,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 120,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 10. Trugo - İstanbul Maslak Shell ──────────────────────────────────────
  {
    id: "trugo-002",
    name: "Trugo - İstanbul Maslak Shell",
    network: "Trugo",
    address: "Büyükdere Cad. No:255, Sarıyer",
    city: "İstanbul",
    district: "Sarıyer",
    latitude: 41.1095,
    longitude: 29.0212,
    overallStatus: "available",
    phone: "0850 222 8 746",
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "gas_station",
    openingHours: { is24h: true },
    venueName: "Shell Maslak",
    hasToggPriority: true,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 11. ZES - İstanbul Avrupa Yakası TEM ───────────────────────────────────
  {
    id: "zes-003",
    name: "ZES - İstanbul TEM Avrupa",
    network: "ZES",
    address: "TEM Otoyolu Mahmutbey Kavşağı, Bağcılar",
    city: "İstanbul",
    district: "Bağcılar",
    latitude: 41.0531,
    longitude: 28.8346,
    overallStatus: "available",
    phone: "0850 166 0 166",
    totalAvailable: 6,
    totalConnectors: 8,
    isGreenEnergy: false,
    locationType: "highway",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: true,
    hasBlockingFee: true,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 350,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 350,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 350,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 3,
        type: "CCS2",
        powerKw: 350,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 4,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 5,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 12. WAT - Bursa Özdilek AVM ────────────────────────────────────────────
  {
    id: "wat-002",
    name: "WAT - Bursa Özdilek AVM",
    network: "WAT",
    address: "İzmir Yolu 5. Km Özdilek Parkway, Nilüfer",
    city: "Bursa",
    district: "Nilüfer",
    latitude: 40.2214,
    longitude: 28.9786,
    overallStatus: "available",
    phone: "0850 999 0 928",
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Özdilek Parkway AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 100,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 100,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 13. 5şarj - İzmir Narlıdere ────────────────────────────────────────────
  {
    id: "5sarj-002",
    name: "5şarj - İzmir Narlıdere",
    network: "5şarj",
    address: "Narlıdere Mah. Mithatpaşa Cad. No:112",
    city: "İzmir",
    district: "Narlıdere",
    latitude: 38.3928,
    longitude: 26.9987,
    overallStatus: "available",
    phone: null,
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "parking",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 100,
        status: "available",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 100,
        status: "available",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 14. EnYakıt - E5 Gebze ─────────────────────────────────────────────────
  {
    id: "enyakit-002",
    name: "EnYakıt - E5 Gebze",
    network: "EnYakıt",
    address: "E5 Karayolu Gebze Mevkii, Gebze",
    city: "Kocaeli",
    district: "Gebze",
    latitude: 40.8021,
    longitude: 29.4317,
    overallStatus: "available",
    phone: "0850 255 0 369",
    totalAvailable: 4,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "highway",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 200,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: 14.9,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 3,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 14.9,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 15. Voltrun - Ankara Çankaya ───────────────────────────────────────────
  {
    id: "voltrun-002",
    name: "Voltrun - Ankara Çankaya",
    network: "Voltrun",
    address: "Tunalı Hilmi Cad. No:98, Çankaya",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.9043,
    longitude: 32.8615,
    overallStatus: "available",
    phone: null,
    totalAvailable: 2,
    totalConnectors: 3,
    isGreenEnergy: false,
    locationType: "workplace",
    openingHours: {
      is24h: false,
      weekdays: "08:00-20:00",
      weekends: "09:00-18:00",
    },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "Type2",
        powerKw: 7.4,
        status: "occupied",
        pricePerKwh: 9.95,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "AC",
      },
    ],
  },

  // ─── 16. ZES - İstanbul Kadıköy ─────────────────────────────────────────────
  {
    id: "zes-004",
    name: "ZES - İstanbul Kadıköy",
    network: "ZES",
    address: "Rıhtım Cad. No:45, Kadıköy",
    city: "İstanbul",
    district: "Kadıköy",
    latitude: 40.9912,
    longitude: 29.0238,
    overallStatus: "available",
    phone: "0850 166 0 166",
    totalAvailable: 2,
    totalConnectors: 3,
    isGreenEnergy: false,
    locationType: "public",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: true,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
    ],
  },

  // ─── 17. Eşarj - Ankara Bilkent AVM ─────────────────────────────────────────
  {
    id: "esarj-003",
    name: "Eşarj - Ankara Bilkent AVM",
    network: "Eşarj",
    address: "Bilkent AVM, Üniversiteler Mah. Dumlupınar Blv., Çankaya",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.8724,
    longitude: 32.7533,
    overallStatus: "available",
    phone: "0850 346 0 346",
    totalAvailable: 4,
    totalConnectors: 6,
    isGreenEnergy: true,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Bilkent AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 360,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 360,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CCS2",
        powerKw: 150,
        status: "occupied",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 3,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: 13.5,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 4,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 5,
        type: "Type2",
        powerKw: 22,
        status: "available",
        pricePerKwh: 13.5,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 18. Trugo - Antalya Migros ──────────────────────────────────────────────
  {
    id: "trugo-003",
    name: "Trugo - Antalya Migros",
    network: "Trugo",
    address: "100. Yıl Blv. No:78, Kepez",
    city: "Antalya",
    district: "Kepez",
    latitude: 36.9328,
    longitude: 30.6578,
    overallStatus: "available",
    phone: "0850 222 8 746",
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "09:00-22:00",
      weekends: "09:00-22:00",
    },
    venueName: "Migros Antalya AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 180,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: 15.36,
        blockingFeePerMin: null,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.78,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 19. WAT - Konya Anatolium ───────────────────────────────────────────────
  {
    id: "wat-003",
    name: "WAT - Konya Anatolium AVM",
    network: "WAT",
    address: "Anatolium Konya AVM, Horozluhan Mah., Selçuklu",
    city: "Konya",
    district: "Selçuklu",
    latitude: 37.9238,
    longitude: 32.4928,
    overallStatus: "available",
    phone: "0850 999 0 928",
    totalAvailable: 2,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Anatolium Konya AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 100,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 100,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 20. ZES - İzmir Forum AVM ──────────────────────────────────────────────
  {
    id: "zes-005",
    name: "ZES - İzmir Forum AVM",
    network: "ZES",
    address: "Forum Bornova AVM, Kazımdirik Mah., Bornova",
    city: "İzmir",
    district: "Bornova",
    latitude: 38.4668,
    longitude: 27.2203,
    overallStatus: "available",
    phone: "0850 166 0 166",
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Forum Bornova AVM",
    hasToggPriority: false,
    hasBlockingFee: true,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 150,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: 16.49,
        blockingFeePerMin: 0.5,
        tier: "HPC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: 0.5,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 12.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 21. Beefull - İstanbul Üsküdar ─────────────────────────────────────────
  {
    id: "beefull-001",
    name: "Beefull - İstanbul Üsküdar",
    network: "Beefull",
    address: "Hakimiyet-i Milliye Cad. No:12, Üsküdar",
    city: "İstanbul",
    district: "Üsküdar",
    latitude: 41.0237,
    longitude: 29.0147,
    overallStatus: "available",
    phone: null,
    totalAvailable: 2,
    totalConnectors: 3,
    isGreenEnergy: false,
    locationType: "parking",
    openingHours: { is24h: true },
    venueName: null,
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 60,
        status: "available",
        pricePerKwh: 13.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 60,
        status: "available",
        pricePerKwh: 13.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.99,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },

  // ─── 22. Otojet - Gaziantep Sanko Park ──────────────────────────────────────
  {
    id: "otojet-001",
    name: "Otojet - Gaziantep Sanko Park",
    network: "Otojet",
    address: "Sanko Park AVM, İncilipınar Mah., Şahinbey",
    city: "Gaziantep",
    district: "Şahinbey",
    latitude: 37.0731,
    longitude: 37.3832,
    overallStatus: "available",
    phone: null,
    totalAvailable: 3,
    totalConnectors: 4,
    isGreenEnergy: false,
    locationType: "mall",
    openingHours: {
      is24h: false,
      weekdays: "10:00-22:00",
      weekends: "10:00-22:00",
    },
    venueName: "Sanko Park AVM",
    hasToggPriority: false,
    hasBlockingFee: false,
    connectors: [
      {
        id: 0,
        type: "CCS2",
        powerKw: 80,
        status: "available",
        pricePerKwh: 13.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 1,
        type: "CCS2",
        powerKw: 80,
        status: "available",
        pricePerKwh: 13.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 2,
        type: "CHAdeMO",
        powerKw: 50,
        status: "available",
        pricePerKwh: 13.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
      {
        id: 3,
        type: "Type2",
        powerKw: 22,
        status: "occupied",
        pricePerKwh: 13.49,
        pricePerKwhHPC: null,
        blockingFeePerMin: null,
        tier: "DC",
      },
    ],
  },
];
